info = {"message": "2021-05-14_17:29", "commit": "69ff7ca5bc16c4ba6bfdf3ac0ba39c7586385c1a", "date": "2021-05-14 17:29:36 +0800", "branch": "lastest101", "version": "1.0.1+174.g69ff7ca5.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
